.github/workflows/validation.yaml
When running integration tests Hilla runs a maven goal as a forked process but it fails if the extension artifacts are not in the local maven repository.
=> chore: split build and test in validation worflow

pom.xml
Always run maven flatten plugin to resolve revision property, so that locally installed artifacts have a complete and usable POM file.
=> chore: always flatten POMs to resolve revision property

hilla-shaded-deps/pom.xml, pom.xml
IntelliJ IDEA fails to handle the hilla-shaded-deps module, causing compilation errors to be shown in the IDE.
This change adds a maven configuration to attach the same artifact to the maven project with a custom classifier, so that IDEA is able to correctly find the classes. However, the plugin execution is always skipped, so it does not affect the build process.
=> chore: help IntelliJ IDEA to handle hilla-shaded-deps module

pom.xml
Hide bot from the contributors list in changelog.
Uses same config as in the configuration example https://jreleaser.org/guide/latest/reference/release/changelog.html#_contributors
=> chore: hide bots from contributors list

.github/dependabot.yml
This configuration prevents dependabot to create PR to upgrade quarkus, hilla and vaadin-quarkus with latest version for branch 1.0.
Fixes #42
=> chore: configure dependabot for protected branches

.github/workflows/format-pr.yaml, .github/workflows/validation.yaml
A new job in validation workflow checks that formatting is ok, and if not, it prevents the PR from being merged.
If the code is not well formatted, the label `format:required` is applied to the PR and a comment reports the file that should be checked, a full diff and formatting instructions.
Otherwise, the `format:checked` label is applied.
Another workflow, triggered by the `auto-format` label, applies formatting to the PR and pushes the changes to the PR branch.
The push automatically triggers a new validation.
Closes #67
Closes #68
=> chore(actions): add formatting check and auto-format PR jobs

.github/workflows/release.yaml
The Bootstrap test fails when Hilla executes maven to generate endpoints because then forked process is not aware of the release property and it seraches for wrong quarkus-hilla dependencies
=> chore(actions): skip integration test during release build

.github/workflows/validation-not-required.yaml
If a PR contains only changes to files ignored by the validation workflow, the build and test job is not executed and its status is pending, preventing the PR to being merged.
This change introduces an additional workflow that marks as good PR that contains changes to ignored files.
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks\#handling-skipped-but-required-checks for more information.
=> fix(actions): skip validation check for ignored paths (#119) (CP: 1.0)

.github/workflows/cherry-picks.yaml
Provides automation of the cherry-pick process, by adding a 'target/X.Y' label to a PR. Only merged PRs can be picked. The label can be applied before or after merge.
Closes #123
=> chore: add cherry-pick workflow

.github/workflows/validation-nightly.yaml
The workflow validates the extension against Hilla snapshots and Java versions. It runs every night at 1:00 AM, but it can also be triggered manually.
Closes #36
Closes #145
=> chore(actions): add workflow for nightly validations

pom.xml
Having the Hilla BOM before the Vaadin BOM should allow Hilla dependencies to have higher priority in dependency management.
=> chore: swap the import order of Vaadin and Hilla BOMs

.github/actions/run-validation/action.yaml, .github/workflows/validation.yaml
Uses selenide system property to force the browser binary that should be used for integration test.
=> chore: force downloaded chrome binary path

.github/workflows/validation.yaml
Uses selenide system property to force the browser binary that should be used for integration test.
=> chore: force downloaded chrome binary path (#171) (CP: 1.0)

hilla-jandex/pom.xml, pom.xml
JBoss jandex-maven-plugin is archived, smallrye plugin is mentioned in quarkus documentation
=> chore: update jandex-maven-plugin

deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/AuthFormBuildItem.java, deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java, runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaSecurityPolicy.java, runtime/src/main/java/com/github/mcollovati/quarkus/hilla/HillaSecurityRecorder.java
In the vertx-http snpashot version, the configuration classes have been migrated from a concrete class with public field to [at]ConfigMapping annotated interface. To allow the extension to work with both version, this change takes configuration values directly from the Config object.
=> refactor: use Config to get form authentication settings

deployment/pom.xml, runtime/pom.xml
It's likely that a Hilla application will use jakarta validation annotations, so it makes sense adding the hibernate-validator as extension dependency.
=> chore: add hibernate-validator dependency

deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/ReactiveEndpointTest.java
=> test: increase timeout while waiting for push response

.github/actions/run-validation/action.yaml, .github/workflows/validation-nightly.yaml, integration-tests/hybrid-smoke-tests/pom.xml, integration-tests/smoke-tests/pom.xml, pom.xml
To prevent issues with npm packages when using Hilla versions different from the one used to build the lock file the action will delete the lock file and node_modules folder for integration test modules.
It also computes the correct Vaadin platform snapshot version for the hybrid test module.
=> chore(actions): refactor snapshot validation

.github/actions/run-validation/action.yaml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/validation.yaml
Allows to disable chrome installation when there are incompatibilities with installed chromedriver.
This is a temporary workaround. A proper fix would be disinstall global chromedriver or remove it from path, so that the correct driver can be installed by selenium manager
=> chore(actions): disable chrome install based on repository variable

.github/workflows/validation.yaml
Allows to disable chrome installation when there are incompatibilities with installed chromedriver. This is a temporary workaround. A proper fix would be disinstall global chromedriver or remove it from path, so that the correct driver can be installed by selenium manager
=> chore(actions): disable chrome install based on repository variable (CP: 1.0)

etc/release-version-rules.xml
Used by release process to pin Hilla version, when POM defines a SNAPSHOT
=> chore(actions): add rules for hilla version upgrade detection

.github/actions/run-validation/action.yaml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/validation.yaml
Allows to disable chrome installation when there are incompatibilities with installed chromedriver. This is a temporary workaround. A proper fix would be disinstall global chromedriver or remove it from path, so that the correct driver can be installed by selenium manager
(cherry picked from commit c03fe9531faea61d333de6173c7f60610d1fdac1)
=> chore(actions): disable chrome install based on repository variable (#377) (CP 2.2)

.github/actions/run-validation/action.yaml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/validation.yaml
Allows to disable chrome installation when there are incompatibilities with installed chromedriver. This is a temporary workaround. A proper fix would be disinstall global chromedriver or remove it from path, so that the correct driver can be installed by selenium manager
(cherry picked from commit c03fe9531faea61d333de6173c7f60610d1fdac1)
=> chore(actions): disable chrome install based on repository variable (#377) (CP: 2.1)

runtime-react/pom.xml, runtime/pom.xml
Hilla dev-tools database plugin breaks application startup because it makes use of Spring classes.
This change disables the plugin by removing its ServiceLoader descriptor
Fixes #485
=> fix: disable dev-tools database plugin

pom.xml
For backward compatibility with GH actions that must run on other branches. Prevents getting real Hilla version that may not always match the Vaadin platform version.
=> chore: use hilla property for vaadin-bom

runtime-commons/src/main/java/com/github/mcollovati/quarkus/hilla/SpringReplacements.java
Prevents failures if CurrentIdentityAssociation bean is not present.
Fixes #963
=> fix: handle missing security info

integration-tests/pom.xml
Quarkus tests reuse the same application instance, unless tests define different profiles or test resources. However, the JVM is always the same and Flow reuses the existing dev server instance.
This can cause errors when the application is restarted if frontend files are forcibly deleted.
This change make sure that the dev server is always stopped and restarted.
=> test: prevent reusing dev-server

commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaNativeProcessor.java, commons/hilla-shaded-deps/pom.xml, commons/runtime/pom.xml
Removes from the native build Hilla classes referencing Spring Data classes to preven failures during native image creation.
=> fix: ignore spring related classes in native build

README.md, commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java, commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/OffendingMethodCallsReplacer.java, commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/TransferTypesPluginClassVisitor.java, commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/vaadinplugin/VaadinPlugin.java, commons/deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/MutinyReactiveEndpointTest.java, commons/deployment/src/test/java/com/github/mcollovati/quarkus/hilla/deployment/endpoints/MutinyReactiveEndpoint.java, commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/MutinyEndpointSubscription.java, commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointControllerConfiguration.java, commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointInvoker.java, commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/build/TransferTypesPluginPatch.java, integration-tests/react-smoke-tests/src/main/frontend/views/MutinyPushView.tsx, integration-tests/react-smoke-tests/src/main/frontend/views/PushView.tsx, integration-tests/react-smoke-tests/src/main/java/com/example/application/ClockService.java, integration-tests/react-smoke-tests/src/main/java/com/example/application/MutinyClockService.java, integration-tests/react-smoke-tests/src/test/java/com/example/application/MutinyPushNativeIT.java, integration-tests/react-smoke-tests/src/test/java/com/example/application/MutinyPushTest.java, integration-tests/react-smoke-tests/src/test/java/com/example/application/PushNativeIT.java, integration-tests/react-smoke-tests/src/test/java/com/example/application/PushTest.java
Allows Hilla endpoints to specify Mutiny Multi as return type for reactive endpoints. Also introduces MutinyEndpointSubscription as a Mutiny alternative to Hilla EndpointSubscription to provide unsubscribe callback.
Fixes #1028
=> feat: add support for mutiny based reactive endpoints

commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaNativeProcessor.java, commons/hilla-shaded-deps/pom.xml
Some Vaadin components like Grid and Combobox have methods that refers to the VaadinSpringDataHelpers class from vaadin-spring artifact, causing native build to fail because the class cannot be found.
This change adds the missing class to the shaded deps in order to fix native build.
Fixes #1221
=> fix: add VaadinSpringDataHelpers to shaded deps

commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/security/HillaSecurityRecorder.java
Quarkus 3.19 refactors HTTP configuration in a way that cookie name is available only at runtime.
This change move the configuration retrival inside the Supplier returned by setupFormAuthenticationMechanism so that the configuration can be retrieved.
Fixes #1270
=> fix: retrieve cookie name at runtime

.github/workflows/validation-native.yaml, commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaNativeProcessor.java
Vaadin Quarkus extension introduced build steps for native image. This change prevents the execution of the same steps from Quarkus Hilla extension, if the Vaadin native processor is available.
=> fix: check for Vaadin native process

commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/DataRepositorySupportBuiltItem.java, commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java, commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaNativeProcessor.java
The published capabilities are for internal use only. They are not interesting for other extensions and can perhaps be replaced with custom build items.
Fixes #1602
=> chore: remove provided capabilities

integration-tests/panache-extension-support-tests/src/test/java/com/example/application/AutoCrudTest.java, integration-tests/spring-extension-support-tests/src/test/java/com/example/application/AutoCrudTest.java
Vaadin switched to native popover for dialog components. However, it looks like selenium does not handle correctly visibility of elements in a popover since they are actually visible but their opacity is 1, resulting in test failures when the element is clicked.
This change introduces a workaround to click a button in a popover by using Selenium Actions API.
=> test: fix confirm dialog verifications
